from os import listdir
blogname = 'Blog'

fw = open('index.html', 'w')
fw.write('<!DOCTYPE html>\n')
fw.write('<html>\n')
fw.write('\t<head>\n')
fw.write('\t\t<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n')
fw.write('\t\t<title>{}</title>\n'.format(blogname))
fw.write('\t</head>\n')
fw.write('\t<body>\n')
fw.write('\t\t\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n')
fw.write('\t\t<nav class=\"navbar navbar-dark bg-dark\">\n')
fw.write('\t\t\t<div class=\"container-fluid\">\n')
fw.write('\t\t\t\t<a class=\"navbar-brand\" href=\"/\">{}</a>\n'.format(blogname))
fw.write('\t\t\t\t<button class=\"btn btn-light\" type=\"button\" onclick=\"window.location.href=\'/login\';\">Login</button>\n')
fw.write('\t\t\t</div>\n')
fw.write('\t\t</nav>\n')
fw.write('\t\t<div style=\"padding-top: 75px\" class=\"container\">\n')
fw.write('\t\t\t<ul class=\"list-group\">\n')
for f in listdir('posts'):
	fw.write('\t\t\t\t<a href=\"{}\" class=\"list-group-item list-group-item-action\">{}</a>\n'.format('/posts/{}'.format(f), f[:-5]))
fw.write('\t\t\t</ul>\n')
fw.write('\t\t</div>\n')
fw.write('\t</body>\n')
fw.write('</html>\n')
